title: Fábio Freitas | @0xfabiof
description: > # this means to ignore newlines until "baseurl:"
  MSc Information Security @ DCC - FCUP
  Security Engineer & Penetration Tester @ Euronext
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Fábio Freitas # add your name
author-img: ff.jpeg # add your photo
about-author: MSc Information Security @ DCC - FCUP
about-author2: Security Engineer & Penetration Tester @ Euronext
social-twitter: 0xfabiof # add your Twitter handle
social-github: 0xfabiof # add your Github handle
social-linkedin: fábio-freitas-396834150 # add your Linkedin handle
social-email: fabiofreitaseu19@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
